app:
  keep_login: 1
  tasks:
    status_default_css_class: "default"
    default_status_content: "Open"
  models:
    user:
      name_max_length: 50
      email_max_length: 255
      password_max_length: 8
    course:
      name_max_length: 50
      course_per_page: 1
