app:
  default_image: "course-2.jpg"
  keep_login: 1
  course_subject:
    status:
      started: 1
      finished: 2
  tasks:
    status_default_css_class: "default"
    default_status_content: "Open"
    tasks_per_page: 5
  users:
    users_per_page: 5
  models:
    user:
      name_max_length: 50
      email_max_length: 255
      password_max_length: 8
      default_password_lenght: 4
    course:
      name_max_length: 50
      course_per_page: 1
    subject:
      subject_per_page: 4
      name_max_length: 100
      description_max_length: 200
  developement:
    host: localhost
    port: 3000
    action_mailer:
      address: smtp.gmail.com
      port: 587
      domain: example.com
  controller:
    namespace_for_admin: "Admin"
    namespace_for_trainer: "Trainer"
    namespace_for_trainee: ""
